//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.DBS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributionPlace
    {
        public DistributionPlace()
        {
            this.Assigns = new HashSet<Assign>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Assign> Assigns { get; set; }
    }
}
