//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.DBS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodDetail
    {
        public int Id { get; set; }
        public string RestaurantName { get; set; }
        public string RestaurantAddress { get; set; }
        public int Qty { get; set; }
    
        public virtual FoodDetail FoodDetails1 { get; set; }
        public virtual FoodDetail FoodDetail1 { get; set; }
    }
}
