//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.DBS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Zero_HungerEntities1 : DbContext
    {
        public Zero_HungerEntities1()
            : base("name=Zero_HungerEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Assign> Assigns { get; set; }
        public DbSet<Distribution> Distributions { get; set; }
        public DbSet<DistributionPlace> DistributionPlaces { get; set; }
        public DbSet<Distributor> Distributors { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<FoodDetail> FoodDetails { get; set; }
        public DbSet<Food> Foods { get; set; }
        public DbSet<Restaurant> Restaurants { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<Delivary> Delivaries { get; set; }
    }
}
